spring.application.name=project-a-team04-backend

# MySQL datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Recreate schema on startup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=${JWT_SECRET}

# Brevo
brevo.api-key=${BREVO_API_KEY}
brevo.sender-email=dev.kickbell@gmail.com
brevo.sender-name=wis-2020-manager

# Custom application properties
app.backend-url=${BACKEND_URL:http://localhost:8080}
app.frontend-url=${FRONTEND_URL:http://localhost:4000}

